import React, { FormEvent, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { invoke } from "@tauri-apps/api/core";
import "./style.css";

type Status = { serviceVersion:string; state:string; port:string; simState:string; registration:string; signalRssi:number; lastError:string };
type Port = { name:string; vid:number; pid:number; label:string; available:boolean; dedicatedAt:boolean };
type Settings = { usbVid:number; usbPid:number; portOverride:string; baud:number; callTimeoutSeconds:number; uploadPacingMs:number; maxAudioBytes:number; ussdCode:string; ussdTimeoutSeconds:number; currency:string; lowBalanceThreshold:number; balanceRegex:string };
const empty: Status = { serviceVersion:"â€”",state:"Connecting",port:"",simState:"â€”",registration:"â€”",signalRssi:0,lastError:"" };
const tabs = ["Dashboard","SMS","Calls","Balance","Diagnostics","Settings"] as const;

function App(){
 const [tab,setTab]=useState<(typeof tabs)[number]>("Dashboard"); const [status,setStatus]=useState(empty);
 useEffect(()=>{let active=true; const refresh=()=>invoke<Status>("get_status").then(x=>active&&setStatus(x)).catch(e=>active&&setStatus(s=>({...s,state:"Service unavailable",lastError:String(e)}))); refresh(); const timer=setInterval(refresh,2000); return()=>{active=false;clearInterval(timer)}},[]);
 return <div className="shell"><aside><h1>A7670</h1><p>Modem Console</p><nav>{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav></aside><main><header><div><span className={`dot ${status.state==="Ready"?"ready":""}`}/>{status.state}</div><small>{status.port||"No port"}</small></header><section><h2>{tab}</h2>{tab==="Dashboard"?<Dashboard status={status}/>:tab==="Diagnostics"?<Diagnostics status={status}/>:tab==="Settings"?<SettingsPage/>:<Unavailable name={tab}/>}</section></main></div>
}
function Dashboard({status}:{status:Status}){const guidance=status.state.toLowerCase().includes("busy")?`Close the application using ${status.port||"the AT port"}; reconnection is automatic.`:status.state!=="Ready"?"Check the USB cable, SIMCom driver, and Windows service.":"";return <><div className="cards"><Card label="Service" value={status.serviceVersion}/><Card label="Modem" value={status.state}/><Card label="COM port" value={status.port}/><Card label="SIM" value={status.simState}/><Card label="Network" value={status.registration}/><Card label="Signal" value={`${status.signalRssi} RSSI`}/></div>{(status.lastError||guidance)&&<div className="warning"><strong>Connection guidance</strong><p>{status.lastError||guidance}</p></div>}</>}
function Diagnostics({status}:{status:Status}){const [ports,setPorts]=useState<Port[]>([]),[error,setError]=useState(""),[command,setCommand]=useState("AT+CSQ"),[history,setHistory]=useState<{at:string;command:string;lines:string[]}[]>([]),[running,setRunning]=useState(false); const refresh=()=>invoke<Port[]>("list_ports").then(setPorts).catch(e=>setError(String(e))); useEffect(()=>{void refresh()},[]); const run=async(e:FormEvent)=>{e.preventDefault();setRunning(true);setError("");try{const lines=await invoke<string[]>("execute_at",{command});setHistory(h=>[{at:new Date().toLocaleTimeString(),command,lines},...h])}catch(e){setError(String(e))}finally{setRunning(false)}};return <div className="stack"><div className="panel"><div className="panel-title"><strong>COM candidates</strong><button onClick={refresh}>Refresh</button></div>{ports.length?<table><thead><tr><th>Port</th><th>VID:PID</th><th>Interface</th><th>Availability</th></tr></thead><tbody>{ports.map(p=><tr key={p.name}><td>{p.name}{p.dedicatedAt&&<span className="badge">preferred</span>}</td><td>{hex(p.vid)}:{hex(p.pid)}</td><td>{p.label||"USB serial interface"}</td><td>{p.available?"Available":"Busy"}</td></tr>)}</tbody></table>:<p>No matching COM candidates detected.</p>}</div><form className="panel" onSubmit={run}><strong>Guarded AT console</strong><p className="muted">Interactive payload, SMS, file upload, and USSD commands are blocked.</p><div className="row"><input value={command} onChange={e=>setCommand(e.target.value)} maxLength={512}/><button disabled={running||status.state!=="Ready"}>{running?"Runningâ€¦":"Execute"}</button></div>{error&&<p className="form-error">{error}</p>}<div className="terminal">{history.length?history.map((x,i)=><div key={i}><span>{x.at}</span> &gt; {x.command}<pre>{x.lines.join("\n")}</pre></div>):<p>No commands in this session.</p>}</div></form></div>}
function SettingsPage(){const [form,setForm]=useState<Settings|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("");useEffect(()=>{invoke<Settings>("get_settings").then(setForm).catch(e=>setError(String(e)))},[]);if(!form)return <div className="panel">{error||"Loading settingsâ€¦"}</div>;const field=(key:keyof Settings,label:string,type="text")=><label>{label}<input type={type} value={String(form[key])} onChange={e=>setForm({...form,[key]:type==="number"?Number(e.target.value):e.target.value})}/></label>;const save=async(e:FormEvent)=>{e.preventDefault();setError("");setMessage("");try{setForm(await invoke<Settings>("update_settings",{settings:form}));setMessage("Settings validated and applied for this app session.")}catch(e){setError(String(e))}};return <form className="panel settings" onSubmit={save}><div className="grid">{field("usbVid","USB VID","number")}{field("usbPid","USB PID","number")}{field("portOverride","Port override")}{field("baud","Baud","number")}{field("callTimeoutSeconds","Call timeout (seconds)","number")}{field("uploadPacingMs","Upload pacing (ms)","number")}{field("maxAudioBytes","Audio limit (bytes)","number")}{field("ussdCode","USSD code")}{field("ussdTimeoutSeconds","USSD timeout (seconds)","number")}{field("currency","Currency")}{field("lowBalanceThreshold","Low-balance threshold","number")}{field("balanceRegex","Balance regex")}</div>{error&&<p className="form-error">{error}</p>}{message&&<p className="success">{message}</p>}<button type="submit">Save settings</button></form>}
function Card({label,value}:{label:string;value:string}){return <article><small>{label}</small><strong>{value||"â€”"}</strong></article>};function Unavailable({name}:{name:string}){return <div className="panel"><strong>Not implemented in this build</strong><p>{name} requires its complete daemon workflow and is intentionally unavailable.</p></div>}function hex(value:number){return value.toString(16).toUpperCase().padStart(4,"0")}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);


