import { type FormEvent, useEffect, useState } from "react";
import { invoke } from "../api";
import type { AudioSyncState, CallData, Record, UploadedAudio } from "../types";
import { formatBytes } from "../format";
import { History } from "../components";

export function Calls({ready}:{ready:boolean}){
  const[destination,setDestination]=useState(""),[records,setRecords]=useState<Record[]>([]),[library,setLibrary]=useState<UploadedAudio[]>([]),[selected,setSelected]=useState<File|null>(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[progress,setProgress]=useState(0),[status,setStatus]=useState(""),[error,setError]=useState("");
  const[syncState,setSyncState]=useState<AudioSyncState>("pending");
  const current=library.find(audio=>audio.isCurrent)||null;
  const active=records.some(record=>["waiting-for-answer","playback-delay","playing","hang-up-failed"].includes(record.state));
  const releaseFailed=records.some(record=>record.state==="hang-up-failed");
  const refresh=async()=>{try{const data=await invoke<CallData>("get_call_data");setRecords(data.calls);setLibrary(data.audio);setSyncState(data.audioSyncState);return data}catch(e){setError(String(e));return null}};
  useEffect(()=>{let stopped=false,timer=0;const poll=async()=>{const data=await refresh();if(stopped)return;const callActive=data?.calls.some(record=>["waiting-for-answer","playback-delay","playing","hang-up-failed"].includes(record.state))??false;timer=window.setTimeout(()=>void poll(),callActive?750:5000)};void poll();return()=>{stopped=true;window.clearTimeout(timer)}},[active]);
  const choose=(file:File|null)=>{setError("");setStatus("");if(!file){setSelected(null);return}if(!file.name.toLowerCase().endsWith(".amr")){setSelected(null);setError("Select an AMR-NB file with an .amr extension.");return}setSelected(file)};
  const upload=async()=>{if(!selected)return;setUploading(true);setProgress(0);setError("");setStatus("Reading AMR file...");try{const reader=selected.stream().getReader(),chunks:Uint8Array[]=[];let received=0;for(;;){const{done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.length;setProgress(Math.round(received/selected.size*50))}const data=new Uint8Array(received);let offset=0;for(const chunk of chunks){data.set(chunk,offset);offset+=chunk.length}setStatus("Uploading to modem...");setProgress(60);await invoke<UploadedAudio>("upload_audio",{name:selected.name,data:Array.from(data)});setSelected(null);setProgress(100);setStatus("Audio uploaded and selected for calls.");await refresh()}catch(e){setError(String(e));setStatus("Upload failed; the previous library entry remains unchanged.")}finally{setUploading(false)}};
  const selectAudio=async(id:string)=>{setError("");try{await invoke("select_audio",{audioId:id});setStatus("Audio selection saved.");await refresh()}catch(e){setError(String(e))}};
  const dial=async(e:FormEvent)=>{e.preventDefault();if(!current)return;setBusy(true);setError("");try{await invoke("make_call",{destination,audioId:current.id});await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}};
  const hang=async()=>{setError("");try{await invoke("hang_up");setStatus("Call release confirmed.");await refresh()}catch(e){setError(`Hang up was not confirmed. Retry Hang Up; dialing remains blocked. ${String(e)}`);await refresh()}};
  return <div className="stack"><div className="panel audio-upload"><div className="panel-title"><div><strong>AMR audio library</strong><p className="muted">Uploads are validated and retained. Uploading the same filename replaces only that entry.</p></div>{current&&<span className="badge">current</span>}</div><div className="audio-picker"><input type="file" accept=".amr,audio/amr" disabled={active||uploading||syncState!=="ready"} onChange={e=>choose(e.target.files?.[0]||null)}/><button type="button" disabled={!ready||!selected||active||uploading||syncState!=="ready"} onClick={upload}>{uploading?"Uploading...":"Upload audio"}</button></div>{selected&&<p className="muted">Selected: {selected.name} ({formatBytes(selected.size)})</p>}{(uploading||progress>0)&&<progress max="100" value={progress}/>} {status&&<p className={status.startsWith("Upload failed")?"form-error":"success"}>{status}</p>}{syncState!=="ready"?<p className="muted">{syncState==="deferred"?"Audio synchronization is waiting for the modem.":"Synchronizing audio from modem..."}</p>:library.length?<table className="audio-library"><thead><tr><th>Filename</th><th>Size</th><th>Duration</th><th>Uploaded</th><th>Status</th><th></th></tr></thead><tbody>{library.map(audio=><tr key={audio.id}><td>{audio.name}</td><td>{formatBytes(audio.size)}</td><td>{(audio.durationMs/1000).toFixed(1)} s</td><td>{new Date(audio.createdAtMs).toLocaleString()}</td><td>{audio.isCurrent?<span className="badge">current</span>:"ready"}</td><td><button type="button" disabled={audio.isCurrent||active||uploading||syncState!=="ready"} onClick={()=>void selectAudio(audio.id)}>Select</button></td></tr>)}</tbody></table>:<p className="muted">No audio uploaded. Dialing is disabled.</p>}</div><form className="panel" onSubmit={dial}><strong>Call control</strong><p className="muted">Playback starts after the call is answered. Enter a Vietnamese or international subscriber number; SMS service codes cannot be called.</p><div className="row"><input placeholder="0912345678 or +84912345678" value={destination} onChange={e=>setDestination(e.target.value)}/><button disabled={!ready||syncState!=="ready"||busy||active||!current||!destination}>{busy?"Dialing...":"Dial"}</button><button type="button" className="danger" disabled={!ready||!active} onClick={hang}>{releaseFailed?"Retry Hang Up":"Hang Up"}</button></div>{releaseFailed&&<p className="warning-inline">Release is not yet confirmed. New calls and uploads remain blocked.</p>}{error&&<p className="form-error">{error}</p>}</form><History title="Call history" records={records} empty="No persisted call history."/></div>
}
