import { type FormEvent, useEffect, useState } from "react";
import { invoke } from "../api";
import type { IntegrationSettings, Settings } from "../types";

export function SettingsPage(){
  const[form,setForm]=useState<Settings|null>(null),[integration,setIntegration]=useState<IntegrationSettings|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("");
  useEffect(()=>{Promise.all([invoke<Settings>("get_settings"),invoke<IntegrationSettings>("get_integration_settings")]).then(([core,http])=>{setForm(core);setIntegration(http)}).catch(e=>setError(String(e)))},[]);
  if(!form||!integration)return <div className="panel">{error||"Loading settings…"}</div>;
  const field=(key:keyof Settings,label:string,type="text")=><label>{label}<input type={type} value={String(form[key])} onChange={e=>setForm({...form,[key]:type==="number"?Number(e.target.value):e.target.value})}/></label>;
  const integrationField=(key:"restBindAddress"|"webhookUrl",label:string)=><label>{label}<input value={integration[key]} onChange={e=>setIntegration({...integration,[key]:e.target.value})}/></label>;
  const save=async(e:FormEvent)=>{e.preventDefault();setError("");setMessage("");try{const[core,http]=await Promise.all([invoke<Settings>("update_settings",{settings:form}),invoke<IntegrationSettings>("update_integration_settings",{settings:integration})]);setForm(core);setIntegration({...http,restToken:"",webhookToken:"",clearRestToken:false,clearWebhookToken:false});setMessage("Settings validated and saved. REST URL and token changes apply immediately; bind-address changes require a service restart.")}catch(e){setError(String(e))}};
  return <form className="stack" onSubmit={save}>
    <section className="panel settings"><strong>Modem</strong><div className="grid">{field("usbVid","USB VID","number")}{field("usbPid","USB PID","number")}{field("portOverride","Port override")}{field("baud","Baud","number")}{field("callTimeoutSeconds","Call timeout (seconds)","number")}{field("uploadPacingMs","Upload pacing (ms)","number")}{field("maxAudioBytes","Audio limit (bytes)","number")}{field("currency","Currency")}{field("lowBalanceThreshold","Low-balance threshold","number")}{field("balanceRegex","Balance regex")}</div></section>
    <section className="panel settings"><strong>REST and webhooks</strong><p className="muted">HTTP is intended for a firewall-restricted trusted LAN. Bearer tokens are not encrypted in transit when using HTTP.</p><label><input type="checkbox" checked={integration.restEnabled} onChange={e=>setIntegration({...integration,restEnabled:e.target.checked})}/> Enable REST API</label><div className="grid">{integrationField("restBindAddress","REST bind address (restart required)")}{integrationField("webhookUrl","Webhook URL")}<label>Replace REST bearer token<input type="password" autoComplete="new-password" value={integration.restToken} placeholder={integration.hasRestToken?"Stored token unchanged":"Token required before enabling"} onChange={e=>setIntegration({...integration,restToken:e.target.value,clearRestToken:false})}/></label><label>Replace webhook bearer token<input type="password" autoComplete="new-password" value={integration.webhookToken} placeholder={integration.hasWebhookToken?"Stored token unchanged":"Optional"} onChange={e=>setIntegration({...integration,webhookToken:e.target.value,clearWebhookToken:false})}/></label></div><label><input type="checkbox" checked={integration.clearRestToken} onChange={e=>setIntegration({...integration,clearRestToken:e.target.checked,restToken:""})}/> Clear stored REST token</label><label><input type="checkbox" checked={integration.clearWebhookToken} onChange={e=>setIntegration({...integration,clearWebhookToken:e.target.checked,webhookToken:""})}/> Clear stored webhook token</label></section>
    {error&&<p className="form-error">{error}</p>}{message&&<p className="success">{message}</p>}<button>Save settings</button>
  </form>
}
